### ISSUE TITLE
Could not determine your distribution because multiple packages are providing redhat-release

### ISSUE THREAD

**Issue by lostongoogle** [oracle/centos2ol#28] opened 2020-12-23 17:19 UTC
not sure if there are pre-requisites to the script but im running into the below issue

```
bash centos2ol.sh
Checking for required packages...
Checking your distribution...
Could not determine your distribution because multiple
packages are providing redhat-release:
centos-release-8.2-2.2004.0.2.el8.x86_64
centos-linux-release-8.3-1.2011.el8.noarch
```

**Comment by totalamateurhour** [comment] 2020-12-23 17:24
Can you provide some background on how this server was installed or where it's running? Also, can you provide the output of `yum info redhat-release`

**Comment by lostongoogle** [comment] 2020-12-23 17:37
Hi yes,
it is a centos 8 pretty much a fresh install from a few weeks ago.

 yum info redhat-release
Repository cr is listed more than once in the configuration
Repository extras is listed more than once in the configuration
Repository extras-source is listed more than once in the configuration
Repository fasttrack is listed more than once in the configuration
Last metadata expiration check: 0:21:31 ago on Wed 23 Dec 2020 12:14:50 PM
EST.
Error: No matching Packages to list

**Comment by totalamateurhour** [comment] 2020-12-23 18:09
Is it possible you started with CentOS 8.2 and upgraded to 8.3 in a way that left both `centos-linux-release-8.3-1.2011.el8.noarch` and `centos-release-8.2-2.2004.0.2.el8.x86_64` in place?

**Comment by lostongoogle** [comment] 2020-12-23 22:35
Its possible, I may have used an older iso rather than pulling the latest.
Should I simply remove the repositories from etc/yum.repos.d?

**Comment by totalamateurhour** [comment] 2020-12-24 07:32
From what I can tell, the issue is caused by already installed CentOS release RPMs. I don’t think disabling yum repos will help. I’d rather think removing the `centos-release-8.2-2.2004.0.2.el8.x86_64` would get you further along. What I don’t know, is whether doing so has other unintended consequences, in your situation.

**Comment by lostongoogle** [comment] 2020-12-24 10:22
Ok, thanks for the clarification.
Its not a live prod box but rather a dev one so I am allowed to break it I
will try to delete that and see what happens.

**Comment by totalamateurhour** [comment] 2020-12-26 08:55
OK, please let us know what your findings are.

**Comment by totalamateurhour** [comment] 2021-01-11 11:08
Closed as there were no further updates.

**Closed by totalamateurhour** 2021-01-11 11:08 UTC
