### ISSUE TITLE
Script fails to get repo files from oracle for centos 7

### ISSUE THREAD

**Issue by bamorrow** [oracle/centos2ol#81] opened 2021-06-16 14:55 UTC
Script fails at below code as seems repo files from oracle changed.

    echo "Downloading Oracle Linux yum repository file..."
           
                if ! curl -o "switch-to-oraclelinux.repo" "${yum_url}/${repo_file}"; then
      
                          exit_message "Could not download $repo_file from $yum_url.
           
                Are you behind a proxy? If so, make sure the 'http_proxy' environment
            
                variable is set with your proxy address."
      
                      fi
            
                ;;

**Comment by totalamateurhour** [comment] 2021-06-16 15:11
Can you run the script this way to see the actual values: `sudo bash -x centos2ol.sh`

**Comment by totalamateurhour** [comment] 2021-06-22 17:37
@bamorrow Are you able to reproduce this running the script with `bash -x`?

**Comment by bamorrow** [comment] 2021-06-22 18:51
looks like it can get the file now

**Comment by totalamateurhour** [comment] 2021-06-22 19:28
Thanks for letting us know. Not sure what the root cause would have been as the file hasn’t moved for years. I’ll close this issue, but let us know if you run into any others.

**Closed by totalamateurhour** 2021-06-22 19:28 UTC
Labels: question
